root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[watcher]
cmd = ["echo 'test"]
exts = ["go", "tpl", "tmpl", "html"]



[build]
  args_bin = []
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", ".dist", ".git", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  cmd = "go build -o ./tmp/main ./src/*.go"
  full_bin = "./tmp/main"
  include_dir = ["src"]
  include_ext = ["go", "tpl", "tmpl", 
  # "html"
  ]
  include_file = []
  kill_delay = "0s"
  log = "air.log"
  poll = false
  poll_interval = 0
  pre_cmd = []
  post_cmd = ["kill -9 $(lsof -t -i:42069 -sTCP:LISTEN)"]
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
